name: Build And Publish Java Container Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
      image_name:
        required: true
        type: string
      tag:
        type: string
      module_name:
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      if: ${{ true && github.repository != 'beergode/shared-pipeline-templates' }}
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository_name }}
        ref: main

    - name: Set up JDK
      if: ${{ true && github.repository != 'beergode/shared-pipeline-templates' }}
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Build with Gradle
      if: ${{ true && github.repository != 'beergode/shared-pipeline-templates' }}
      run: |
        chmod +x ./gradlew
        ./gradlew clean build -x test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        dockerfile: ./${{ inputs.module_name }}/Dockerfile

    - name: Login to GitHub Container Registry
      if: ${{ github.repository != 'beergode/shared-pipeline-templates' }}
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.registry_username }}
        password: ${{ secrets.registry_password }}

    - name: Build and push Docker image
      if: ${{ github.repository != 'beergode/shared-pipeline-templates' }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ inputs.image_name }}:latest
          ghcr.io/${{ inputs.image_name }}:${{ inputs.tag }}