name: Maven Build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          OMNI_DB_HOST: ${{vars.OMNI_DB_HOST}}
          OMNI_DB_PORT: ${{vars.OMNI_DB_PORT}}
          OMNI_DB_NAME: ${{vars.OMNI_DB_NAME}}
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        if: ${{ true }}
        run:
          mvn clean install

      - name: Run Tests
        if: ${{ true }}
        run: mvn test