name: Maven Build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
      module_name:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ true && github.repository != 'beergode/shared-pipeline-templates' }}
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository_name }}
          ref: main

      - name: Set up JDK
        if: ${{ true && github.repository != 'beergode/shared-pipeline-templates' }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Cache gradle dependencies
        if: ${{ true && github.repository != 'beergode/shared-pipeline-templates' }}
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

      - name: Build with Gradle
        run:
          ./gradlew {{ inputs.module_name }}:build {{ inputs.module_name }}:bootJar -PskipInfraSetup -Dorg.gradle.daemon=false --rerun-tasks
