name: Build And Publish Container Image

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.registry_username }}
        password: ${{ secrets.registry_password }}

    - name: Build and push Docker image
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ inputs.image_name }}:latest
          ghcr.io/${{ inputs.image_name }}:${{ inputs.tag }}