name: Semantic versioning

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      dry_run:
        required: true
        type: boolean
    secrets:
      repo_token:
        required: true

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      #Dry run to estimate the next tag version
      - name: Minor version Dry run
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.repo_token }}
          WITH_V: true
          DRY_RUN: ${{ inputs.dry_run }}