name: Semantic versioning

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      dry_run:
        required: true
        type: boolean

jobs:
  tagging:
    runs-on: ubuntu-latest
    outputs:
      newTag: ${{ steps.taggerDryRun.outputs.new_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: numanturkeri/omnisystem
          ref: main

      #Dry run to estimate the next tag version
      - name: Minor version Dry run
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: ${{ inputs.dry_run }}