name: Semantic versioning

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      dry_run:
        required: true
        type: boolean
    outputs:
      newTag:
        description: "The newest tag of the repository"
        value: ${{ jobs.tagging.outputs.newTag }}

jobs:
  tagging:
    runs-on: ubuntu-latest
    outputs:
      newTag: ${{ steps.taggerDryRun.outputs.new_tag }}
    steps:
      - name: Checkout repository
        if: ${{ github.repository != 'numanturkeri/shared-pipeline-templates' }}
        uses: actions/checkout@v3
        with:
          repository: numanturkeri/omnisystem
          ref: main

      #Dry run to estimate the next tag version
      - name: Minor version Dry run
        if: ${{ true && github.repository != 'numanturkeri/shared-pipeline-templates' }}
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: ${{ inputs.dry_run }}

      - name: Set up environment variable
        run: echo "THE_TAG=$FIRST_TAG" >> $GITHUB_ENV
        env:
          FIRST_TAG: ${{ steps.taggerDryRun.outputs.new_tag }}